# Workflow GitHub pour publier un package Python sur PyPI lors de la création d'une release
name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code source
      - uses: actions/checkout@v4

      # Installer la version spécifiée de Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"  # Version de Python utilisée pour le build

      # Construire les distributions (source + wheel)
      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      # Upload des distributions pour un usage ultérieur
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      # URL du projet PyPI (remplacez `reedsolomon` par le nom exact de votre package)
      url: https://pypi.org/project/reedsolomon/

    steps:
      # Télécharger les distributions construites
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # Publier les distributions sur PyPI
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
