name: Python Tests (unittest)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.4]

    steps:
      # Vérification du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # Ajouter le répertoire src au PYTHONPATH
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      # Exécution des tests avec unittest
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*.py"
